# Generated by Django 5.1.4 on 2025-01-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_unread_count_user1_chat_unread_count_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='unread_count_user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='unread_count_user2',
        ),
    ]
