# Generated by Django 5.1.4 on 2025-01-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='images/user-default.png', null=True, upload_to='images/'),
        ),
    ]
