# Generated by Django 5.1.4 on 2025-01-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='images/group-default.png', null=True, upload_to='images/'),
        ),
    ]
