# Generated by Django 5.1.4 on 2025-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='images/group-default.jpg', null=True, upload_to='images/'),
        ),
    ]
